### ISSUE TITLE
Weekly progress 3-28-2015

### ISSUE THREAD

**Issue by pyroesque** [CSUCyberSec/HPWebInterface#14]
This week I've been working on finishing up the setup wizard and merging the graphs that Rachael built with the setup wizard, thanks for creating them Rachael. I have gotten the main dashboard mostly merged and it is looking pretty good! The only thing  I haven't figured out yet is how to connect to the kippo database, utilizing the kippo models that were created in rails. The rails app only seems to connect to the cerburi database, unless I missed something. Maybe you can help clarify this for me. 

The setup wizard is mostly complete, one thing I was thinking may be nice for the oinkcode is some screenshots of getting an account from snort and finding the oinkcode. I can do this, but if someone else needs something to do that would be great as well, plus I think all of my current email addresses are already registered with them.

 The app is really starting to come around, if you guys have things you want to add to it, I believe Jared said that Miles was working on a help and about page, just send them to me and I'll integrate it into the site giving it all the fancy formatting that I've already implemented. 

Another thing that we will want to look at is setting up the server to run on an outward looking ip/port. The default is localhost which means it won't be visible outside of the Pi. If someone wants to make a script that discovers the ip and starts the server on that ip it would probably be very beneficial. 

If you guys want to check what I've done with the app just clone the repository to the pi and run it. It should be set up to run right now. Let me know if there are any issues though.

Another thing I noticed is that the create_mysql script creates a different database then what is currently being used. Most noteably all of the table names are pluralized in the current database whereas they are singular in the script. Not sure if this is an issue just though I'd bring it up. I know rails by default uses pluralized tables but this can be turned off, and has caused me a few headaches.

**Comment by RachaelDinger** [comment]
Chris, I used the chartkick gem to create the graphs in the dashboard. In order to use chartkick you must have an existing model in Rails. When you create a model in rails it creates a database with the components of your model as the fields in that database. Rails specifies certain naming conventions for the model: the model must  start with a capitol letter and must  be singular in form. When you run the rake file to migrate and create your database (in order to have values inside the model) Rails creates a lowercase, plural database table on its own. After much research and troubleshooting, I discovered that if I wanted to utilize a model (and use chartkick) I would have to create a separate database that Rails generated. There is a gem out there called dbmigrate (I believe) that basically moves information from an existing database over into the Rails created database. I did not want to bother with this gem, so I created a series of seed files that are run for different reasons. These seed files basically move data from the existing kippo and snort database tables over to the cerburi table in order for Rails to have information in these models. The code is correct and has been tested. The files created you are seeing were auto-generated by Rails during this process that I followed through a tutorial. There are 3 different seed files: pulledpork, configuration, and production. The production seed should be ran during normal operation - depending on the amount of information in the snort and kippo database, the process to update the cerburi database can be completed in about fifteen seconds. The pulledpork seed takes about 10 minutes to complete, and should only be completed when new definitions are loaded. The configuration seed should only be ran when changes are made to the user interface that affect the way in which kippo's clients and authorization is set up. 

Utilizing a database just for cybercerburi will allow the interface to pick and choose how much information should be retained from the snort and kippo logs, as these do not have a limit on how many events can be recorded. This also limits reading of the snort and kippo database from multiple processes -- as when the Pi is powered on, kippo and snort are constantly writing to these tables -- as of right now the event table in the snort database has close to 1,000 entries and counting. Every time the dashboard page is loaded the models pull information from the cerburi database -- which is a lot faster than trying to read from the snort and kippo databases as they are being written to. I originally just used a mysql query script and Google API to just read these tables, however the load time for the dashboard screen was very high -- almost 45 seconds. In an effort to decrease load time I moved over to the chart kick gem and decided to utilize a rails database that would only bother the snort and kippo databases during certain intervals. This has vastly cut down on the load time of the pages, and has helped alleviate the Pi's processing load. 

Finally, I was under the impression that Jared communicated with you that it probably wasn't a good idea to work on the demo project until we have it finalized this coming Thursday and can upload a newer image. Until Thursday, I would advise to not work on it so that you are not repeating efforts to sync up the projects (if you chose to do so). There have been numerous changes to the dashboard page and other pages have been added that shows further details from the entries in the database. Also, Jared has been able to access the Pi dashboard from within CSU's network from another computer, so the outward facing port problem is a non-issue at this time. You just have to specify the IP port of the cyber cerburi.

**Comment by RachaelDinger** [comment]
I will clean up the Rpi image we have and mark the existing rails application as demo in a zip file. There are a couple of programs that can be uninstalled still that are taking up a lot of memory on the Pi. Once this is completed I will upload the cleaner image for you to utilize.

Let one us know when you have the final ready to go. Please upload the image to the google drive. One of the team can then copy this final image to all of the Rpi's for next years team before storage.

**Comment by RachaelDinger** [comment]
Jared and I cleaned up the Rpi -- we were able to free up about 1.9 GB of space. We also went ahead and installed a demo version of Aanval to test the configuration (per a request from their marketing team). Aanval works great and doesn't take up a lot of space -- I think that next year's team will definitely have a head start equipped with this tool. 

Not sure if everyone has read Joel's email - but he would like us to only reference our past work in the new paper. That is fine, but it will require that our part of the software is completed and can be tested in-house before we finish writing this paper. 

Chris - when do you think that you can be completely done on your end? We will send you the "final" code for what we have on the dashboard by the end of the week so you can merge it/change it/ do whatever with it. 

We will probably need about two weeks to write the final write-up and take adequate screen shots and complete testing using the Kali Linux setup  here in the lab. The final paper is due May 3rd, so we would need a somewhat completed copy of the project by April 19th if possible. 

Chris - please advise on how to best support you so we can wrap this project up and move into the final tasks for this semester.

**Comment by pyroesque** [comment]
The setup wizard will be done by the end of the week. It's pretty much good to go right now but I want to do a little more with encrypting the passwords. I should be good on my end when you guys upload the final image. Please let me know if there is anything you need from me for the final paper.
