### ISSUE TITLE
Set-Up Wizard 

### ISSUE THREAD

**Issue by RachaelDinger** [CSUCyberSec/HPWebInterface#7]
After working very hard today on trying to get the .conf files correct, I think that the interface's set-up wizard should auto-generate these based on the user's input. 

I wanted to compile a list of .conf files that have to be created, and where they are stored:

1) snort.conf -- is stored at /etc/snort/
2) classification.conf -- stored at /etc/snort/
2) barnyard2.conf -- is stored at /etc/snort/
3) pulledpork.conf -- is stored at /etc/snort/
4) the crontab file for updating pulled pork

There is also an initialization file that needs to be written, but I think that these are "hard" settings and really only have to be written once -->
1) snort initialization file is at:  /etc/init.d/snortbarn
2) apache2 initialization file is at: /etc/php5/apache2/php.ini

Also -- BASE settings (front end for Snort database handling)  will need to be automatically configured by the wizard (if possible)
1) BASE page (hosted by Apache2) is at: https://IPAddress/base

**Comment by RachaelDinger** [comment]
Also -- the mysql permissions will have to be generated by the wizard as well: for instance the following will have to be generated per new database user to allow for permissions

grant usage on snort.* to <new_user>@<insert IP address>;
grant usage on archive.* to <new_user>@<insert IP address>;
set password for <new_user>@<insert IP address>=PASSWORD('snort');
grant all privileges on snort.* to <new_user>@<insert IP address>;
grant all privileges on archive.* to <new_user>@<insert IP address>;
flush privileges;

**Comment by pyroesque** [comment]
The wizard needs to be able to either automatically sign the user up for a snort account and pull the oinkcode down or instruct the user on how to do so. May even consider setting snort up to pull down new definitions without an oinkcode if the user doesn't want to set this up.

**Comment by RachaelDinger** [comment]
If the user doesn't want to update definitions, they can always use the default definitions that come pre-loaded with PulledPork (that we are loading right now) -- then we can just disable the script that updates them (its called contab). Or we could just not ever run PulledPork for that user, by never executing it in the init file when the pi is turned on. Either way, I think that there should be three options:
1) register for PulledPork & get a new OinkCode (have a link to www.snort.org  and screen shots to show you how to find the oinkcode once registered)
2) Don't want to register, but would like to use default definitions that are pre-loaded (with the understanding that these definitions will not ever be updated)
3) Do not use PulledPork at all

--not sure if we could get the oinkcode for them. I believe that you have to confirm your email before you can actually log into snort as a registered user. That would make this process really hard to automate.

**Comment by RachaelDinger** [comment]
-- not sure how we would get new definitions without an oinkcode that is valid, as this has to be inserted in specific places in the PulledPork.conf file, and you have to actively connect and validate to update definitions.

**Comment by miles00** [comment]
Hey guys, we can use pretty much any programming language for file I/O, but I think it would be a good idea to stick with Ruby since we've been trying to learn it. The setup wizard can just pass the ruby program the argument we care about, and ruby should have an easy time making the changes we need to the file. We for sure want pulledpork so registering the email would probably be left to the user to make sure they get their oinkcode, and in the mean time default rules with no oinkcode would be used. I'll post the initialization/bootup script later today.

**Comment by pyroesque** [comment]
made some headway on the setup wizard today. started creating the two main pages to create an admin name and password and getting the oinkcode from the user. I'm having a little trouble with some of the CSS, but part of that is just not having access to the internet while I was building it.

**Comment by pyroesque** [comment]
Setup wizard is complete. Things to note:
1) there is a file in the root folder called first.run. The program check for this file and if it exists the setup wizard is the first page displayed, if this file does not exist then the root path is set to the dashboard. After you input the oinkcode this file is deleted and you are taken to the dashboard.

2)the oinkcode is inserted into pulledpork.conf, this means that the current user, meaning pi right now, needs to have permission to edit this file. As it stands right now this file has full permissions for all users and is owned by snort:snort, so this isn't an issue. However having these files completely open isn't good practice and in the future will need to be changed. But for now it works.

My version still can't get into the kippo portion of the database so I've commented that part out so that the dashboard will at least show something.
